from config0 import *
V = 'V'
Fname = ''
AeroToRun = ''
test_on = 1
multi=1
NumProcess='multiprocessing.cpu_count()-1'
save_modes = 1
load_modes = 0
save_gammas = 1
load_gammas = 0
save_qs = 0
load_qs = 0
save_sol = 0
load_sol = 0
run_fem = 1
run_modes = 1
run_coefficients = 1
run_modal_solution = 0
run_displacements = 0
run_cg = 0
save_folder='results_13-5-2023_15-27'