V = 'V'                                        # Variables input file
Fname = 'F'                                    # Forces input file
AeroToRun = ''                                 # Aerodynamic input file
InitC = ''                                     # Initial conditions (q0s) inputs
save_folder= Fname                             # Relative folder to save results
test_on = 0                                    # Running a test 
multi=1                                        # Run integrals in parallel
NumProcess='multiprocessing.cpu_count()-1'     # Number of cores in the parallel computations
save_modes = 1
load_modes = 0
save_gammas = 1
load_gammas = 0
save_qs = 1
load_qs = 0
save_Xs=1
load_Xs=0
save_sol = 1
load_sol = 0
run_fem = 1
run_modes = 1
run_coefficients = 1
run_modal_solution = 1
run_displacements = 1
run_cg = 1
ODESolver = 'RK4'
