from config0 import *
V = 'V1'
Fname = 'F1'
AeroToRun = ''
InitC = ''
test_on = 1
multi=1
NumProcess = 'multiprocessing.cpu_count()-1'
save_modes = 1
load_modes = 0
save_gammas = 1
load_gammas = 0
save_qs = 1
load_qs = 0
save_sol = 1
load_sol = 0
run_fem = 0
run_modes = 0
run_coefficients = 0
run_modal_solution = 1
run_displacements = 1
run_cg = 0
ODESolver = 'RK4'
save_folder='results_double14-5-2023_14-0'