from config0 import *
V = 'V'
Fname = 'Fdead3d'
AeroToRun = ''
InitC = ''
test_on = 1
multi=1
NumProcess = 'multiprocessing.cpu_count()-1'
save_folder = 'results3d'
save_modes = 1
load_modes = 0
save_gammas = 1
load_gammas = 1
save_qs = 1
load_qs = 0
save_sol = 1
load_sol = 0
run_fem = 1
run_modes = 1
run_coefficients = 1
run_modal_solution = 1
run_displacements = 1
run_cg = 1
ODESolver = 'RK4'
save_folder='3D/results_16-5-2023_12-40'